monitor_stocks:
  - name: "卫星化学"
    code: "002648.SZ"
  - name: "我爱我家"
    code: "000560.SZ"
  - name: "长安汽车"
    code: "000625.SZ"
  - name: "湖北宜化"
    code: "000422.SZ"
  - name: "华鲁恒升"
    code: "600426.SH"
  - name: "恒瑞医药"
    code: "600276.SH"
  - name: "欧派家具"
    code: "603833.SH"
  - name: "天赐材料"
    code: "002709.SZ"
  - name: "通威股份"
    code: "600438.SH"
  - name: "隆基绿能"
    code: "601012.SH"
  - name: "双良节能"
    code: "600481.SH"
  - name: "华东医药"
    code: "000963.SZ"
    monitor: "false"
  - name: "中国电建"
    code: "601669.SH"
